package com.microframework.generator.client;

import com.microframework.generator.dto.Sessions;
import com.microframework.generator.dto.SessionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int countByExample(SessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int deleteByExample(SessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int insert(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int insertSelective(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    List<Sessions> selectByExample(SessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    Sessions selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sessions record, @Param("example") SessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sessions record, @Param("example") SessionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sessions record);
}