package com.microframework.generator.client;

import com.microframework.generator.dto.SysUserAppRoles;
import com.microframework.generator.dto.SysUserAppRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserAppRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int countByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int insert(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int insertSelective(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    List<SysUserAppRoles> selectByExample(SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    SysUserAppRoles selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUserAppRoles record, @Param("example") SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUserAppRoles record, @Param("example") SysUserAppRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUserAppRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_app_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserAppRoles record);
}