package com.microframework.generator.dto;

public class Sessions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.session
     *
     * @mbggenerated
     */
    private String session;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.id
     *
     * @return the value of sessions.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.id
     *
     * @param id the value for sessions.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.session
     *
     * @return the value of sessions.session
     *
     * @mbggenerated
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.session
     *
     * @param session the value for sessions.session
     *
     * @mbggenerated
     */
    public void setSession(String session) {
        this.session = session;
    }
}